### ISSUE TITLE
Synchronize Ranks via Vault.

### ISSUE THREAD

**Issue by ParadauxDev** [ParadauxDev/HiberniaDiscord#9]
Through the use of the bot syncronize roles between servers,

**Comment by egg82** [comment]
This may be out-of-scope for this particular project. Far as I'm aware, this is a project that syncs chat (and maybe some other related stuff) between Discord and a Minecraft server. I'm not sure creating/syncing an entire ranking system is a good idea here. We'd want to keep things in-scope to avoid feature creep and a bloated codebase/final product.

**Comment by ParadauxDev** [comment]
Always possible to have it as an external addon
